-- MySQL Script generated by MySQL Workbench
-- Wed Jun 27 20:52:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema indocope
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema indocope
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `indocope` DEFAULT CHARACTER SET utf8 ;
USE `indocope` ;

-- -----------------------------------------------------
-- Table `indocope`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indocope`.`Users` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `birthday` VARCHAR(45) NOT NULL,
  `money` DECIMAL(5,3) NOT NULL DEFAULT 0.0,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indocope`.`timetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indocope`.`timetable` (
  `idUser` INT NULL,
  `status` TINYINT NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `money` DECIMAL(5,3) NOT NULL,
  `idBlogger` INT NOT NULL,
  `id` INT NOT NULL,
  `tick` DECIMAL(5,3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_timetable_Users1_idx` (`idBlogger` ASC),
  INDEX `fk_timetable_Users2_idx` (`idUser` ASC),
  CONSTRAINT `fk_timetable_Users1`
    FOREIGN KEY (`idBlogger`)
    REFERENCES `indocope`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timetable_Users2`
    FOREIGN KEY (`idUser`)
    REFERENCES `indocope`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indocope`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indocope`.`cards` (
  `idcard` INT NOT NULL,
  `idUser` INT NOT NULL,
  `card_number` VARCHAR(45) NOT NULL,
  `card_name` VARCHAR(45) NOT NULL,
  `card_date` DECIMAL(5,3) NOT NULL,
  PRIMARY KEY (`idcard`),
  INDEX `fk_cards_Users_idx` (`idUser` ASC),
  CONSTRAINT `fk_cards_Users`
    FOREIGN KEY (`idUser`)
    REFERENCES `indocope`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indocope`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indocope`.`request` (
  `idrequest` INT NOT NULL,
  `idUser` INT NOT NULL,
  `id_timetable` INT NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrequest`),
  INDEX `fk_request_timetable1_idx` (`id_timetable` ASC),
  CONSTRAINT `fk_request_timetable1`
    FOREIGN KEY (`id_timetable`)
    REFERENCES `indocope`.`timetable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indocope`.`translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indocope`.`translation` (
  `idtranslation` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idBlogger` INT NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtranslation`),
  INDEX `fk_translation_Users1_idx` (`idUser` ASC),
  INDEX `fk_translation_Users2_idx` (`idBlogger` ASC),
  CONSTRAINT `fk_translation_Users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `indocope`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_translation_Users2`
    FOREIGN KEY (`idBlogger`)
    REFERENCES `indocope`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
